// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHY4EV6U49RvZu5_qoHB-NxOzts_baiDI',
    appId: '1:1015981962581:web:99fb75b0557f70c4502bdc',
    messagingSenderId: '1015981962581',
    projectId: 'test-5a324',
    authDomain: 'test-5a324.firebaseapp.com',
    databaseURL: 'https://test-5a324.firebaseio.com',
    storageBucket: 'test-5a324.appspot.com',
    measurementId: 'G-VGT495NRT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOpNL61hjFVMOHfp13UfQ633t_MPXNHcc',
    appId: '1:1015981962581:android:05a77ba21e83cb0b502bdc',
    messagingSenderId: '1015981962581',
    projectId: 'test-5a324',
    databaseURL: 'https://test-5a324.firebaseio.com',
    storageBucket: 'test-5a324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6tsQzmz4Af5DacTUMlH12mgweHHjNVQs',
    appId: '1:1015981962581:ios:0c3641bcb6193a58502bdc',
    messagingSenderId: '1015981962581',
    projectId: 'test-5a324',
    databaseURL: 'https://test-5a324.firebaseio.com',
    storageBucket: 'test-5a324.appspot.com',
    androidClientId: '1015981962581-6ti775m2pqkpfhdg3l04ditp3g9d4eva.apps.googleusercontent.com',
    iosBundleId: 'com.example.kejaksaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6tsQzmz4Af5DacTUMlH12mgweHHjNVQs',
    appId: '1:1015981962581:ios:0c3641bcb6193a58502bdc',
    messagingSenderId: '1015981962581',
    projectId: 'test-5a324',
    databaseURL: 'https://test-5a324.firebaseio.com',
    storageBucket: 'test-5a324.appspot.com',
    androidClientId: '1015981962581-6ti775m2pqkpfhdg3l04ditp3g9d4eva.apps.googleusercontent.com',
    iosBundleId: 'com.example.kejaksaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHY4EV6U49RvZu5_qoHB-NxOzts_baiDI',
    appId: '1:1015981962581:web:1dd3ee8ca5b60b6e502bdc',
    messagingSenderId: '1015981962581',
    projectId: 'test-5a324',
    authDomain: 'test-5a324.firebaseapp.com',
    databaseURL: 'https://test-5a324.firebaseio.com',
    storageBucket: 'test-5a324.appspot.com',
    measurementId: 'G-VXGTJPPH9H',
  );

}
